AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'dbapp

  Sample SAM Template for dbapp

  '
Globals:
  Function:
    Timeout: 3
Resources:
  DbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://com.dhenton.sambucket/3d3f4b7de6832daa3f4cdb4ebff84fb5
      Environment:
        Variables:
          CONNECTION_STRING: null
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        Db:
          Type: Api
          Properties:
            Path: /db
            Method: get
Outputs:
  DbApi:
    Description: API Gateway endpoint URL for Prod stage for Db  function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/db/
  DbFunction:
    Description: Db  Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DbFunction
      - Arn
  DbFunctionIamRole:
    Description: Implicit IAM Role created for Db  function
    Value:
      Fn::GetAtt:
      - DbFunctionRole
      - Arn
