AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dbapp

  Sample SAM Template for dbapp
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DbFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dbcode/
      Environment:
        Variables:
          CONNECTION_STRING:  # will come from env.json locally and SSM when on the aws server
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        Db:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /db
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DbApi:
    Description: "API Gateway endpoint URL for Prod stage for Db  function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/db/"
  DbFunction:
    Description: "Db  Lambda Function ARN"
    Value: !GetAtt DbFunction.Arn
  DbFunctionIamRole:
    Description: "Implicit IAM Role created for Db  function"
    Value: !GetAtt DbFunctionRole.Arn
