AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  find-comics

  Sample SAM Template for find-comics
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  FindComicsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: find-comics/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        FindComics:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /find-comics
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FindComicsApi:
    Description: "API Gateway endpoint URL for Prod stage for FindComics function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/FindComics/"
  FindComicsFunction:
    Description: "Comics Lambda Function ARN"
    Value: !GetAtt FindComicsFunction.Arn
  # FindComicsFunctionIamRole:
  #   Description: "Implicit IAM Role created for   Comics function"
  #   Value: !GetAtt FindComicsFunctionRole.Arn
  FindComicsFunctionIamRole:
    Description: "Implicit IAM Role created for Find Comics function"
    Value: arn:aws:iam::235926060045:role/basicLamdba
    