AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'find-stories

  Sample SAM Template for find-stories

  '
Globals:
  Function:
    Timeout: 15
Resources:
  FindStoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://com.awsdhenton.marvel.findstories/a7d4116850a61b5d5995f0760cb13844
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        FindStories:
          Type: Api
          Properties:
            Path: /find-stories
            Method: get
Outputs:
  FindStoriesApi:
    Description: API Gateway endpoint URL for Prod stage for FindStories function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/FindStories/
  FindStoriesFunction:
    Description: Stories Lambda Function ARN
    Value:
      Fn::GetAtt:
      - FindStoriesFunction
      - Arn
  FindStoriesFunctionIamRole:
    Description: Implicit IAM Role created for Find Stories function
    Value: arn:aws:iam::235926060045:role/basicLamdba
