AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'DBAccess

  DynamoDB for Restaurants

  '
Globals:
  Function:
    Timeout: 15
Resources:
  DbAccessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://com.awsdhenton.restaurants/a421f7f81c4b6fa7b1737f956d50b74b
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          NODE_ENV: VALUE
          CORS_DOMAINS: VALUE
Outputs:
  DbAccessFunction:
    Description: Stories Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DbAccessFunction
      - Arn
  DbAccessFunctionIamRole:
    Description: Implicit IAM Role created for DbAccess function
    Value: arn:aws:iam::235926060045:role/basicLamdba
