AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DBAccess

  DynamoDB for Restaurants
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  DbAccessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dbaccess/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Environment: 
        Variables:
            NODE_ENV: VALUE
            CORS_DOMAINS: VALUE
      # Events:
      #   DbAccess:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /restaurants
      #       Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # DbAccessApi:
  #   Description: "API Gateway endpoint URL for Prod stage for DbAccess function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/DbAccess/"
  DbAccessFunction:
    Description: "Stories Lambda Function ARN"
    Value: !GetAtt DbAccessFunction.Arn
  # DbAccessFunctionIamRole:
  #   Description: "Implicit IAM Role created for   Stories function"
  #   Value: !GetAtt DbAccessFunctionRole.Arn
  DbAccessFunctionIamRole:
    Description: "Implicit IAM Role created for DbAccess function"
    Value: arn:aws:iam::235926060045:role/basicLamdba
    