AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-sizer

  Sample SAM Template for image-sizer
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ImageHandlerFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      RoleName: !Join 
        - ''
        - - !Ref 'AWS::StackName'
          - ImageHandlerFunctionRole
          - '-'
          - !Ref 'AWS::Region'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: >-
              Resource name validated and found to pose no risk to updates that
              require replacement of this resource.
  ImageHandlerPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogStream'
              - 'logs:CreateLogGroup'
              - 'logs:PutLogEvents'
            Resource: !Sub >-
              arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:ListBucket'
            Resource:
              - 'arn:aws:s3:::*'
          
      PolicyName: !Join 
        - ''
        - - !Ref 'AWS::StackName'
          - ImageHandlerPolicy
      Roles:
        - !Ref ImageHandlerFunctionRole
  ImageSizerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      FunctionName: imageSizer
      Timeout: 10
      Role: !GetAtt ImageHandlerFunctionRole.Arn
      Runtime: nodejs10.x
  
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
 
  ImageSizerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ImageSizerFunction.Arn
  ImageSizerFunctionIamRole:
    Description: "Implicit IAM Role created for Image Sizer function"
    Value: !GetAtt ImageHandlerFunctionRole.Arn
