AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
Resources:
  SSMReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam.awsdhenton.com.bucket/9505609ce46d4ba9c4039f0137e50e1d
      Role: arn:aws:iam::235926060045:role/basicLamdba
      Handler: app.lambdaHandler
      FunctionName: ssmReader
      Timeout: 10
      Runtime: nodejs10.x
Outputs:
  SSMReaderFunction:
    Description: SSMReader Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SSMReaderFunction
      - Arn
