AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
Resources:
  SSMReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam.awsdhenton.com.bucket/a90064da266374567b6f482958ec3f2a
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        SSMReader:
          Type: Api
          Properties:
            Path: /ssmReader
            Method: get
Outputs:
  SSMReaderFunction:
    Description: SSMReader Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SSMReaderFunction
      - Arn
  SSMReaderFunctionIamRole:
    Description: Implicit IAM Role created for SSMReader function
    Value:
      Fn::GetAtt:
      - SSMReaderFunctionRole
      - Arn
