AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'create restaurant db tables'
 
Resources:
    Restaurants:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: Restaurants
        SSESpecification: 
          SSEEnabled: True
        AttributeDefinitions: 
            - AttributeName: id
              AttributeType: S
            # only need to define attributes that are part of the keys
            # - AttributeName: name
            #   AttributeType: S
            # - AttributeName: zipCode
            #   AttributeType: S
            # - AttributeName: city
            #   AttributeType: S
            # - AttributeName: state
            #   AttributeType: S
            # - AttributeName: version
            #   AttributeType: N

        KeySchema: 
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Reviews:
        Type: AWS::DynamoDB::Table
        Properties: 
            TableName: Reviews
            SSESpecification: 
                SSEEnabled: True
            AttributeDefinitions: 
                - AttributeName: restaurantId
                  AttributeType: S
                - AttributeName: id
                  AttributeType: S
                # - AttributeName: starRating
                #   AttributeType: N
                # - AttributeName: reviewListing
                #   AttributeType: S
                # - AttributeName: stampDate
                #   AttributeType: S

            KeySchema: 
            - AttributeName: id
              KeyType: HASH
            - AttributeName: restaurantId
              KeyType: RANGE
            ProvisionedThroughput:  
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            GlobalSecondaryIndexes:
            - IndexName: RestaurantReviews
              KeySchema:
              - AttributeName: restaurantId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANGE
              Projection:
                ProjectionType: KEYS_ONLY
              ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
          